import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { FormEvent, useState } from "react";
import { useAuth } from "@/contexts/auth-context";
import {
    GetServerSideProps,
    GetServerSidePropsContext,
    GetStaticPathsResult,
} from "next";
import { parseCookies } from "nookies";
import { withSSRGuest } from "@/utils/with-ssr-guest";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const { isAuthenticated, signIn } = useAuth();

    const handleSubmit = async (event: FormEvent) => {
        event.preventDefault();
        await signIn({ email, password });
    };
    return (
        <>
            <Head>
                <title>Next.js Authentication</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <form className={styles.main} onSubmit={handleSubmit}>
                <input
                    placeholder="Email"
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                />
                <input
                    placeholder="Password"
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                />
                <button type="submit">Entrar</button>
            </form>
        </>
    );
}

export const getServerSideProps = withSSRGuest(async (ctx) => {
    return {
        props: {},
    };
});
