import { SearchResults } from "@/components/search-results";
import Head from "next/head";
import { FormEvent, useCallback, useState } from "react";

export default function Home() {
    const [search, setSearch] = useState("");
    const [results, setResults] = useState({ totalPrice: 0, data: [] });
    const formatter = Intl.NumberFormat("pt-BR", {
        currency: "BRL",
        style: "currency",
    });
    const handleSearch = async (event: FormEvent) => {
        event.preventDefault();
        if (!search.trim()) return;
        const response = await fetch(
            `http://localhost:3333/products?q=${search}`
        );
        const data = await response.json();

        const totalPrice = data.reduce(
            (total: number, product: { price: number }) =>
                total + product.price,
            0
        );

        const products = data.map((product: { price: number }) => ({
            ...product,
            formattedPrice: formatter.format(product.price),
        }));
        setResults({ data: products, totalPrice });
    };

    const addToWishlist = useCallback((id: number) => {
        console.log(id);
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1>Search</h1>

                <form onSubmit={handleSearch}>
                    <input
                        type="text"
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                    />
                    <button type="submit">Buscar</button>
                    <SearchResults
                        results={results.data}
                        totalPrice={results.totalPrice}
                        onAddToWishlist={addToWishlist}
                    />
                </form>
            </div>
        </>
    );
}
